### ISSUE TITLE
False negative in experiments

### ISSUE THREAD

**Issue by tao-ji** [marcelosousa/progmerge#5]
After reading your paper and your code, I feel confused about computing the post-condition of method calls. It seems that you just assume that  the method call could change the state of the receiver object and don’t analyze the method body. Have you examined the assumption in real-world scenarios?
Based on your assumption, is the example https://github.com/marcelosousa/safemerge/tree/master/benchmarks/experiments/pldi/final/spring-boot/inst46 a false negative?
Since both variants change the different fields of the object _builder_, the state of this object in the merge version is different from the objects in those two variants.

**Comment by marcelosousa** [comment]
Sorry for the very late reply. We also model the fields, so in this case the semantic conflict freedom will be about the state of the all fields in the object 'builder'. In that case, you don't have a conflict and this is why we don't mark it as a false negative. Regarding the side effects of a method, if we have access to the method, they we do a dependence analysis what can be modified by it. Otherwise, our approach can be unsound. This is reported as a limitation. I hope this clarifies.
